server:
  port: 8080
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
spring:
  application:
    name: spring-gateway
  security:
    oauth2:
      client:
        registration:
          auth-server:
            client-name: auth-server
            client-id: gateway
            client-secret: gateway
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/auth-server'
        provider:
          auth-server:
            authorization-uri: http://auth-server:8081/oauth/authorize
            token-uri: http://auth-server:8081/oauth/token
            jwk-set-uri: http://auth-server:8081/oauth/keys
            user-info-uri: http://auth-server:8081/oauth/userinfo
            user-name-attribute: user_name
  cloud:
    gateway:
      routes:
        - id: resource-server
          uri: http://localhost:10000/
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1
            - TokenRelay
